import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.93
blur = false

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 16
