services:
  # Tailscale services
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: greg-zone
    restart: unless-stopped
    volumes:
      - "tailscale-state:/var/lib/tailscale"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    networks:
      - greg-zone-tailscale

  nginx-tailscale:
    image: nginx:alpine
    container_name: nginx-tailscale
    volumes:
      - "./docker/nginx/nginx-tailscale.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/nginx/auth:/etc/nginx/auth:ro"
      - "./docker/nginx/index.html:/usr/share/nginx/html/index.html:ro"
    restart: unless-stopped
    depends_on:
      - copyparty
      - freshrss
      - kiwix
    network_mode: service:tailscale

  # Cloudflare services
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - nginx-cloudflared
    command: tunnel --no-autoupdate run --token ${COPYPARTY_CLOUDFLARED_TOKEN}
    networks:
      - greg-zone-cloudflare
      - greg-zone-tailscale

  nginx-cloudflared:
    image: nginx:alpine
    container_name: nginx-cloudflared
    ports:
      - "9847:80"
    volumes:
      - "./docker/nginx/nginx-cloudflare.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/nginx/auth:/etc/nginx/auth:ro"
    restart: unless-stopped
    depends_on:
      - copyparty
      - freshrss
      - kiwix
    networks:
      - greg-zone-cloudflare
      - greg-zone-tailscale

  # External services (accessible via Cloudflare)
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    ports:
      - "3923:3923"
    user: "1000"
    volumes:
      - "./docker/copyparty/copyparty.conf:/app/copyparty.conf:ro"
      - "/Volumes/Elements:/Volumes/Elements"
      - "/Users/greg.linscheid/Desktop/Mac Vault:/Volumes/Mac Vault"
    restart: unless-stopped
    command: ["--rproxy", "-1", "-c", "/app/copyparty.conf"]
    networks:
      - greg-zone-cloudflare
      - greg-zone-tailscale

  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:latest
    container_name: kiwix
    ports:
      - "8473:8080"
    volumes:
      - "/Volumes/Elements/Local Vault/media/zim:/data"
    restart: unless-stopped
    command: '**/*.zim'
    networks:
      - greg-zone-cloudflare
      - greg-zone-tailscale

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    ports:
      - "49153:80"
    environment:
      - TZ=America/Los_Angeles
      - CRON_MIN=1,31
    volumes:
      - "/Users/greg.linscheid/Desktop/Mac Vault/Greg News/freshrss-data:/var/www/FreshRSS/data"
      - "/Users/greg.linscheid/Desktop/Mac Vault/Greg News/freshrss-extensions:/var/www/FreshRSS/extensions"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
    networks:
      - greg-zone-cloudflare
      - greg-zone-tailscale

  # Internal services (Tailscale only)
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - USER=greg
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - "/Users/greg.linscheid/Desktop/Mac Vault/transmission-config:/config"
      - "/Volumes/Elements/Local Vault/torrent:/downloads"
    restart: unless-stopped
    networks:
      - greg-zone-tailscale

networks:
  greg-zone-cloudflare:
    driver: bridge
  greg-zone-tailscale:
    driver: bridge

volumes:
  tailscale-state:
    driver: local