global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for Docker container metrics
  - job_name: 'docker-stats'
    static_configs:
      - targets: ['docker-stats-exporter:8081']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  # Nginx metrics (if nginx-prometheus-exporter is added later)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-tailscale:9113']
    scrape_interval: 5s
    metrics_path: /metrics

  # Docker services health checks (optional - for service-specific metrics)
  - job_name: 'docker-services'
    static_configs:
      - targets: 
          - 'copyparty:3923'
          - 'freshrss:80'
          - 'kiwix:8080'
          - 'transmission:9091'
    metrics_path: /health
    scrape_interval: 30s
