#!/bin/sh

# Build each subagent for Claude Code and omp from one shared prompt body.
#
# Each agents-src/<name>/ holds:
#   body.md     the prompt, shared by both harnesses
#   shared.yml  frontmatter both harnesses read (name, description)
#   claude.yml  frontmatter only Claude Code reads
#   omp.yml     frontmatter only omp reads
#
# The harnesses disagree on `tools:` and `model:` values, so one file cannot
# serve both. Leave out claude.yml or omp.yml to build for one harness only.
# This script owns the output directories. They hold generated files only.
#
# Usage:
#   sh scripts/gen-agents.sh          Regenerate the agent files
#   sh scripts/gen-agents.sh --check  Fail if the committed files are stale (CI)

set -e

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src_dir="$repo_root/agents-src"
claude_dir="$repo_root/claude-md/.claude/agents"
omp_dir="$repo_root/omp/.omp/agent/agents"

# render <agent source dir> <harness>
render() {
  printf -- '---\n'
  printf '# Generated by scripts/gen-agents.sh from agents-src/%s/. Edit there.\n' "$(basename "$1")"
  cat "$1/shared.yml" "$1/$2.yml"
  printf -- '---\n\n'
  cat "$1/body.md"
}

# generate <claude out dir> <omp out dir>
generate() {
  mkdir -p "$1" "$2"
  rm -f "$1"/*.md "$2"/*.md
  for agent in "$src_dir"/*/; do
    agent="${agent%/}"
    name="$(basename "$agent")"
    if [ -f "$agent/claude.yml" ]; then
      render "$agent" claude > "$1/$name.md"
    fi
    if [ -f "$agent/omp.yml" ]; then
      render "$agent" omp > "$2/$name.md"
    fi
  done
}

case "$1" in
  --check)
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT
    generate "$tmp/claude" "$tmp/omp"
    if ! diff -r "$tmp/claude" "$claude_dir" || ! diff -r "$tmp/omp" "$omp_dir"; then
      echo "Generated agents are stale. Run: sh scripts/gen-agents.sh" >&2
      exit 1
    fi
    echo "Generated agents are up to date."
    ;;
  "")
    generate "$claude_dir" "$omp_dir"
    echo "Generated agents into claude-md/ and omp/."
    ;;
  *)
    echo "Usage: sh scripts/gen-agents.sh [--check]" >&2
    exit 1
    ;;
esac
