containers:
  bedrock:
    - name: bedrock_jordania
      # SSH connection to the minecraft service
      ssh: minecraft:2222
      # itzg's container writes the SSH password to this file
      passwordFile: /jordania/.remote-console.yaml
      worlds:
        - /jordania/worlds/Bedrock level

schedule:
  # Backup every 4 hours
  interval: 4h

trim:
  # Keep all backups for 2 days, then one per day for 14 days total
  trimDays: 2
  keepDays: 14
  # Always keep at least 2 backups
  minKeep: 2