name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Shell Linter
        uses: azohra/shell-linter@latest
